version: "3"
services:
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
    networks:
      - internalNetwork
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - internalNetwork
    restart: always
    volumes:
      - /opt/docker-volumes/mongo/db:/data/db
networks:
  internalNetwork:
    external: false
