version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      #- "./persistence/mysql:/var/lib/mysql"
      - ./api/db_schemas:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  prot:
    image: prot
    tty: true
    stdin_open: true
    restart: always
    # networks:
    #   - internalNetwork
    entrypoint: build/rest_server/api-server
    environment:
      PROT_DB_USER: root
      PROT_DB_SCHEMA: test_prot
      PROT_DB_PASSW: example
      PROT_DB_HOST: db
      PROT_DB_PORT: 3306
    ports:
      - 3000:3000
    expose:
      - "3000"
    depends_on:
    - db
networks:
  internalNetwork:
    external: false
