version: "3"
services:
  db:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      #- "./persistence/mysql:/var/lib/mysql"
      - ./api/db_schemas:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
    security_opt:
    - seccomp:unconfined

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8087
    command: docker-php-entrypoint php -S [::]:8087 -t /var/www/html
  prot:
    image: prot:latest
    tty: true
    stdin_open: true
    restart: always
    # networks:
    #   - internalNetwork
    entrypoint: ./api-server
    environment:
      TZ: Etc/UTC
      PROT_DB_USER: root
      PROT_DB_SCHEMA: prot
      PROT_DB_PASSW: ${DB_PWD}
      PROT_DB_HOST: db
      PROT_DB_PORT: 3306
    ports:
      - 3000:3000
    expose:
      - "3000"
    depends_on:
      - db
  jobs-watcher:
    image: prot:latest
    tty: true
    stdin_open: true
    restart: always
    # networks:
    #   - internalNetwork
    entrypoint: ./jobs-watcher
    environment:
      TZ: Etc/UTC
      PROT_DB_USER: root
      PROT_DB_SCHEMA: prot
      PROT_DB_PASSW: ${DB_PWD}
      PROT_DB_HOST: db
      PROT_DB_PORT: 3306
    depends_on:
      - db
  discovery-rescheduler:
    image: prot:latest
    tty: true
    stdin_open: true
    restart: always
    # networks:
    #   - internalNetwork
    entrypoint: ./discovery-rescheduler
    environment:
      TZ: Etc/UTC
      PROT_DB_USER: root
      PROT_DB_SCHEMA: prot
      PROT_DB_PASSW: ${DB_PWD}
      PROT_DB_HOST: db
      PROT_DB_PORT: 3306
    depends_on:
      - db
networks:
  internalNetwork:
    external: false
