FROM ubuntu:19.04

RUN apt-get update && apt install -y \
apt-utils \
git \
build-essential \
make cmake \
libboost1.67-dev \
libboost-test1.67-dev \
libboost-test-dev \
libboost-program-options1.67-dev