/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Duration_oneOf.h
 *
 * 
 */

#ifndef Duration_oneOf_H_
#define Duration_oneOf_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Duration_oneOf
{
public:
    Duration_oneOf();
    virtual ~Duration_oneOf();

    void validate();

    /////////////////////////////////////////////
    /// Duration_oneOf members

    /// <summary>
    /// 
    /// </summary>
    int32_t getSeconds() const;
    void setSeconds(int32_t const value);

    friend void to_json(nlohmann::json& j, const Duration_oneOf& o);
    friend void from_json(const nlohmann::json& j, Duration_oneOf& o);
protected:
    int32_t m_Seconds;

};

}
}
}
}

#endif /* Duration_oneOf_H_ */
