/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Duration_oneOf.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Duration_oneOf::Duration_oneOf()
{
    m_Seconds = 0;
    
}

Duration_oneOf::~Duration_oneOf()
{
}

void Duration_oneOf::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Duration_oneOf& o)
{
    j = nlohmann::json();
    j["seconds"] = o.m_Seconds;
}

void from_json(const nlohmann::json& j, Duration_oneOf& o)
{
    j.at("seconds").get_to(o.m_Seconds);
}

int32_t Duration_oneOf::getSeconds() const
{
    return m_Seconds;
}
void Duration_oneOf::setSeconds(int32_t const value)
{
    m_Seconds = value;
}

}
}
}
}

