/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Duration.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Duration::Duration()
{
    m_Seconds = 0;
    m_Minutes = 0;
    m_MinutesIsSet = false;
    m_Hours = 0;
    m_HoursIsSet = false;
    m_Days = 0;
    m_DaysIsSet = false;
    m_Weeks = 0;
    m_WeeksIsSet = false;
    m_Months = 0;
    m_MonthsIsSet = false;
    m_Years = 0;
    m_YearsIsSet = false;
    
}

Duration::~Duration()
{
}

void Duration::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Duration& o)
{
    j = nlohmann::json();
    j["seconds"] = o.m_Seconds;
    if(o.minutesIsSet())
        j["minutes"] = o.m_Minutes;
    if(o.hoursIsSet())
        j["hours"] = o.m_Hours;
    if(o.daysIsSet())
        j["days"] = o.m_Days;
    if(o.weeksIsSet())
        j["weeks"] = o.m_Weeks;
    if(o.monthsIsSet())
        j["months"] = o.m_Months;
    if(o.yearsIsSet())
        j["years"] = o.m_Years;
}

void from_json(const nlohmann::json& j, Duration& o)
{
    j.at("seconds").get_to(o.m_Seconds);
    if(j.find("minutes") != j.end())
    {
        j.at("minutes").get_to(o.m_Minutes);
        o.m_MinutesIsSet = true;
    } 
    if(j.find("hours") != j.end())
    {
        j.at("hours").get_to(o.m_Hours);
        o.m_HoursIsSet = true;
    } 
    if(j.find("days") != j.end())
    {
        j.at("days").get_to(o.m_Days);
        o.m_DaysIsSet = true;
    } 
    if(j.find("weeks") != j.end())
    {
        j.at("weeks").get_to(o.m_Weeks);
        o.m_WeeksIsSet = true;
    } 
    if(j.find("months") != j.end())
    {
        j.at("months").get_to(o.m_Months);
        o.m_MonthsIsSet = true;
    } 
    if(j.find("years") != j.end())
    {
        j.at("years").get_to(o.m_Years);
        o.m_YearsIsSet = true;
    } 
}

int32_t Duration::getSeconds() const
{
    return m_Seconds;
}
void Duration::setSeconds(int32_t const value)
{
    m_Seconds = value;
}
int32_t Duration::getMinutes() const
{
    return m_Minutes;
}
void Duration::setMinutes(int32_t const value)
{
    m_Minutes = value;
    m_MinutesIsSet = true;
}
bool Duration::minutesIsSet() const
{
    return m_MinutesIsSet;
}
void Duration::unsetMinutes()
{
    m_MinutesIsSet = false;
}
int32_t Duration::getHours() const
{
    return m_Hours;
}
void Duration::setHours(int32_t const value)
{
    m_Hours = value;
    m_HoursIsSet = true;
}
bool Duration::hoursIsSet() const
{
    return m_HoursIsSet;
}
void Duration::unsetHours()
{
    m_HoursIsSet = false;
}
int32_t Duration::getDays() const
{
    return m_Days;
}
void Duration::setDays(int32_t const value)
{
    m_Days = value;
    m_DaysIsSet = true;
}
bool Duration::daysIsSet() const
{
    return m_DaysIsSet;
}
void Duration::unsetDays()
{
    m_DaysIsSet = false;
}
int32_t Duration::getWeeks() const
{
    return m_Weeks;
}
void Duration::setWeeks(int32_t const value)
{
    m_Weeks = value;
    m_WeeksIsSet = true;
}
bool Duration::weeksIsSet() const
{
    return m_WeeksIsSet;
}
void Duration::unsetWeeks()
{
    m_WeeksIsSet = false;
}
int32_t Duration::getMonths() const
{
    return m_Months;
}
void Duration::setMonths(int32_t const value)
{
    m_Months = value;
    m_MonthsIsSet = true;
}
bool Duration::monthsIsSet() const
{
    return m_MonthsIsSet;
}
void Duration::unsetMonths()
{
    m_MonthsIsSet = false;
}
int32_t Duration::getYears() const
{
    return m_Years;
}
void Duration::setYears(int32_t const value)
{
    m_Years = value;
    m_YearsIsSet = true;
}
bool Duration::yearsIsSet() const
{
    return m_YearsIsSet;
}
void Duration::unsetYears()
{
    m_YearsIsSet = false;
}

}
}
}
}

