/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Frequency.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Frequency::Frequency()
{
    m_Frequency = "";
    
}

Frequency::~Frequency()
{
}

void Frequency::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Frequency& o)
{
    j = nlohmann::json();
    j["frequency"] = o.m_Frequency;
}

void from_json(const nlohmann::json& j, Frequency& o)
{
    j.at("frequency").get_to(o.m_Frequency);
}

std::string Frequency::getFrequency() const
{
    return m_Frequency;
}
void Frequency::setFrequency(std::string const& value)
{
    m_Frequency = value;
}

}
}
}
}

