/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_response_200.h
 *
 * 
 */

#ifndef Inline_response_200_H_
#define Inline_response_200_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_response_200
{
public:
    Inline_response_200();
    virtual ~Inline_response_200();

    void validate();

    /////////////////////////////////////////////
    /// Inline_response_200 members

    /// <summary>
    /// 
    /// </summary>
    std::string getUserId() const;
    void setUserId(std::string const& value);

    friend void to_json(nlohmann::json& j, const Inline_response_200& o);
    friend void from_json(const nlohmann::json& j, Inline_response_200& o);
protected:
    std::string m_User_id;

};

}
}
}
}

#endif /* Inline_response_200_H_ */
