/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_object_2.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object_2::Inline_object_2()
{
    m_Type_of_task = "";
    
}

Inline_object_2::~Inline_object_2()
{
}

void Inline_object_2::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_object_2& o)
{
    j = nlohmann::json();
    j["type_of_task"] = o.m_Type_of_task;
    j["task"] = o.m_Task;
}

void from_json(const nlohmann::json& j, Inline_object_2& o)
{
    j.at("type_of_task").get_to(o.m_Type_of_task);
    j.at("task").get_to(o.m_Task);
}

std::string Inline_object_2::getTypeOfTask() const
{
    return m_Type_of_task;
}
void Inline_object_2::setTypeOfTask(std::string const& value)
{
    m_Type_of_task = value;
}
nlohmann::json Inline_object_2::getTask() const
{
    return m_Task;
}
void Inline_object_2::setTask(nlohmann::json const& value)
{
    m_Task = value;
}

}
}
}
}

