/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_response_200_1.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_response_200_1::Inline_response_200_1()
{
    m_ItemsIsSet = false;
    
}

Inline_response_200_1::~Inline_response_200_1()
{
}

void Inline_response_200_1::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_response_200_1& o)
{
    j = nlohmann::json();
    if(o.itemsIsSet() || !o.m_Items.empty())
        j["items"] = o.m_Items;
}

void from_json(const nlohmann::json& j, Inline_response_200_1& o)
{
    if(j.find("items") != j.end())
    {
        j.at("items").get_to(o.m_Items);
        o.m_ItemsIsSet = true;
    } 
}

std::vector<Inline_response_200_1_items>& Inline_response_200_1::getItems()
{
    return m_Items;
}
void Inline_response_200_1::setItems(std::vector<Inline_response_200_1_items> const& value)
{
    m_Items = value;
    m_ItemsIsSet = true;
}
bool Inline_response_200_1::itemsIsSet() const
{
    return m_ItemsIsSet;
}
void Inline_response_200_1::unsetItems()
{
    m_ItemsIsSet = false;
}

}
}
}
}

