/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_object_1.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object_1::Inline_object_1()
{
    m_Json_str = "";
    m_Json_strIsSet = false;
    
}

Inline_object_1::~Inline_object_1()
{
}

void Inline_object_1::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_object_1& o)
{
    j = nlohmann::json();
    if(o.jsonStrIsSet())
        j["json_str"] = o.m_Json_str;
}

void from_json(const nlohmann::json& j, Inline_object_1& o)
{
    if(j.find("json_str") != j.end())
    {
        j.at("json_str").get_to(o.m_Json_str);
        o.m_Json_strIsSet = true;
    } 
}

std::string Inline_object_1::getJsonStr() const
{
    return m_Json_str;
}
void Inline_object_1::setJsonStr(std::string const& value)
{
    m_Json_str = value;
    m_Json_strIsSet = true;
}
bool Inline_object_1::jsonStrIsSet() const
{
    return m_Json_strIsSet;
}
void Inline_object_1::unsetJson_str()
{
    m_Json_strIsSet = false;
}

}
}
}
}

