/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_object_2.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object_2::Inline_object_2()
{
    m_Form_objIsSet = false;
    
}

Inline_object_2::~Inline_object_2()
{
}

void Inline_object_2::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_object_2& o)
{
    j = nlohmann::json();
    if(o.formObjIsSet())
        j["form_obj"] = o.m_Form_obj;
}

void from_json(const nlohmann::json& j, Inline_object_2& o)
{
    if(j.find("form_obj") != j.end())
    {
        o.m_Form_obj = j.at("form_obj");
        o.m_Form_objIsSet = true;
    } 
}

Object Inline_object_2::getFormObj() const
{
    return m_Form_obj;
}
void Inline_object_2::setFormObj(Object const& value)
{
    m_Form_obj = value;
    m_Form_objIsSet = true;
}
bool Inline_object_2::formObjIsSet() const
{
    return m_Form_objIsSet;
}
void Inline_object_2::unsetForm_obj()
{
    m_Form_objIsSet = false;
}

}
}
}
}

