/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_object.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object::Inline_object()
{
    m_Username = "";
    m_UsernameIsSet = false;
    
}

Inline_object::~Inline_object()
{
}

void Inline_object::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_object& o)
{
    j = nlohmann::json();
    if(o.usernameIsSet())
        j["username"] = o.m_Username;
}

void from_json(const nlohmann::json& j, Inline_object& o)
{
    if(j.find("username") != j.end())
    {
        j.at("username").get_to(o.m_Username);
        o.m_UsernameIsSet = true;
    } 
}

std::string Inline_object::getUsername() const
{
    return m_Username;
}
void Inline_object::setUsername(std::string const& value)
{
    m_Username = value;
    m_UsernameIsSet = true;
}
bool Inline_object::usernameIsSet() const
{
    return m_UsernameIsSet;
}
void Inline_object::unsetUsername()
{
    m_UsernameIsSet = false;
}

}
}
}
}

