/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_object.h
 *
 * 
 */

#ifndef Inline_object_H_
#define Inline_object_H_


#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_object
{
public:
    Inline_object();
    virtual ~Inline_object();

    void validate();

    /////////////////////////////////////////////
    /// Inline_object members

    /// <summary>
    /// 
    /// </summary>
    int32_t getForwardProjection() const;
    void setForwardProjection(int32_t const value);
    bool forwardProjectionIsSet() const;
    void unsetForward_projection();
    /// <summary>
    /// 
    /// </summary>
    int32_t getBackwardsProjection() const;
    void setBackwardsProjection(int32_t const value);
    bool backwardsProjectionIsSet() const;
    void unsetBackwards_projection();

    friend void to_json(nlohmann::json& j, const Inline_object& o);
    friend void from_json(const nlohmann::json& j, Inline_object& o);
protected:
    int32_t m_Forward_projection;
    bool m_Forward_projectionIsSet;
    int32_t m_Backwards_projection;
    bool m_Backwards_projectionIsSet;
};

}
}
}
}

#endif /* Inline_object_H_ */
