/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_response_200.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_response_200::Inline_response_200()
{
    m_User_id = "";
    
}

Inline_response_200::~Inline_response_200()
{
}

void Inline_response_200::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_response_200& o)
{
    j = nlohmann::json();
    j["user_id"] = o.m_User_id;
}

void from_json(const nlohmann::json& j, Inline_response_200& o)
{
    j.at("user_id").get_to(o.m_User_id);
}

std::string Inline_response_200::getUserId() const
{
    return m_User_id;
}
void Inline_response_200::setUserId(std::string const& value)
{
    m_User_id = value;
}

}
}
}
}

