/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_response_200_1_items.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_response_200_1_items::Inline_response_200_1_items()
{
    m_App_id = "";
    m_App_idIsSet = false;
    m_App_name = "";
    m_App_nameIsSet = false;
    
}

Inline_response_200_1_items::~Inline_response_200_1_items()
{
}

void Inline_response_200_1_items::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_response_200_1_items& o)
{
    j = nlohmann::json();
    if(o.appIdIsSet())
        j["app_id"] = o.m_App_id;
    if(o.appNameIsSet())
        j["app_name"] = o.m_App_name;
}

void from_json(const nlohmann::json& j, Inline_response_200_1_items& o)
{
    if(j.find("app_id") != j.end())
    {
        j.at("app_id").get_to(o.m_App_id);
        o.m_App_idIsSet = true;
    } 
    if(j.find("app_name") != j.end())
    {
        j.at("app_name").get_to(o.m_App_name);
        o.m_App_nameIsSet = true;
    } 
}

std::string Inline_response_200_1_items::getAppId() const
{
    return m_App_id;
}
void Inline_response_200_1_items::setAppId(std::string const& value)
{
    m_App_id = value;
    m_App_idIsSet = true;
}
bool Inline_response_200_1_items::appIdIsSet() const
{
    return m_App_idIsSet;
}
void Inline_response_200_1_items::unsetApp_id()
{
    m_App_idIsSet = false;
}
std::string Inline_response_200_1_items::getAppName() const
{
    return m_App_name;
}
void Inline_response_200_1_items::setAppName(std::string const& value)
{
    m_App_name = value;
    m_App_nameIsSet = true;
}
bool Inline_response_200_1_items::appNameIsSet() const
{
    return m_App_nameIsSet;
}
void Inline_response_200_1_items::unsetApp_name()
{
    m_App_nameIsSet = false;
}

}
}
}
}

