/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_object_2.h
 *
 * 
 */

#ifndef Inline_object_2_H_
#define Inline_object_2_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_object_2
{
public:
    Inline_object_2();
    virtual ~Inline_object_2();

    void validate();

    /////////////////////////////////////////////
    /// Inline_object_2 members

    /// <summary>
    /// 
    /// </summary>
    std::string getJsonStr() const;
    void setJsonStr(std::string const& value);
    bool jsonStrIsSet() const;
    void unsetJson_str();
    /// <summary>
    /// 
    /// </summary>
    std::string get() const;
    void set(std::string const& value);
    bool IsSet() const;
    void unset();

    friend void to_json(nlohmann::json& j, const Inline_object_2& o);
    friend void from_json(const nlohmann::json& j, Inline_object_2& o);
protected:
    std::string m_Json_str;
    bool m_Json_strIsSet;
    std::string m_;
    bool m_IsSet;
};

}
}
}
}

#endif /* Inline_object_2_H_ */
