/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_response_200_1.h
 *
 * Returns all the developer, apps_names submited
 */

#ifndef Inline_response_200_1_H_
#define Inline_response_200_1_H_


#include "Inline_response_200_1_items.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// Returns all the developer, apps_names submited
/// </summary>
class  Inline_response_200_1
{
public:
    Inline_response_200_1();
    virtual ~Inline_response_200_1();

    void validate();

    /////////////////////////////////////////////
    /// Inline_response_200_1 members

    /// <summary>
    /// 
    /// </summary>
    std::vector<Inline_response_200_1_items>& getItems();
    void setItems(std::vector<Inline_response_200_1_items> const& value);
    bool itemsIsSet() const;
    void unsetItems();

    friend void to_json(nlohmann::json& j, const Inline_response_200_1& o);
    friend void from_json(const nlohmann::json& j, Inline_response_200_1& o);
protected:
    std::vector<Inline_response_200_1_items> m_Items;
    bool m_ItemsIsSet;
};

}
}
}
}

#endif /* Inline_response_200_1_H_ */
