/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_object_3.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object_3::Inline_object_3()
{
    m_Restart = false;
    m_RestartIsSet = false;
    // m_Response = "";
    m_ResponseIsSet = false;
    
}

Inline_object_3::~Inline_object_3()
{
}

void Inline_object_3::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_object_3& o)
{
    j = nlohmann::json();
    if(o.restartIsSet())
        j["restart"] = o.m_Restart;
    if(o.responseIsSet())
        j["response"] = o.m_Response;
}

void from_json(const nlohmann::json& j, Inline_object_3& o)
{
    if(j.find("restart") != j.end())
    {
        j.at("restart").get_to(o.m_Restart);
        o.m_RestartIsSet = true;
    } 
    if(j.find("response") != j.end())
    {
        o.m_Response = j.at("response");
        o.m_ResponseIsSet = true;
    } 
}

bool Inline_object_3::isRestart() const
{
    return m_Restart;
}
void Inline_object_3::setRestart(bool const value)
{
    m_Restart = value;
    m_RestartIsSet = true;
}
bool Inline_object_3::restartIsSet() const
{
    return m_RestartIsSet;
}
void Inline_object_3::unsetRestart()
{
    m_RestartIsSet = false;
}
nlohmann::json Inline_object_3::getResponse() const
{
    return m_Response;
}
void Inline_object_3::setResponse(nlohmann::json const& value)
{
    m_Response = value;
    m_ResponseIsSet = true;
}
bool Inline_object_3::responseIsSet() const
{
    return m_ResponseIsSet;
}
void Inline_object_3::unsetResponse()
{
    m_ResponseIsSet = false;
}

}
}
}
}

