/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_response_200_2.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_response_200_2::Inline_response_200_2()
{
    m_Name = "";
    m_Picture = "";
    m_PictureIsSet = false;
    m_Starts = 0.0;
    m_StartsIsSet = false;
    m_Tags = "";
    m_TagsIsSet = false;
    m_Developer = "";
    m_DeveloperIsSet = false;
    m_Description = "";
    m_DescriptionIsSet = false;
    m_Downloads = 0;
    m_DownloadsIsSet = false;
    
}

Inline_response_200_2::~Inline_response_200_2()
{
}

void Inline_response_200_2::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_response_200_2& o)
{
    j = nlohmann::json();
    j["name"] = o.m_Name;
    if(o.pictureIsSet())
        j["picture"] = o.m_Picture;
    if(o.startsIsSet())
        j["starts"] = o.m_Starts;
    if(o.tagsIsSet())
        j["tags"] = o.m_Tags;
    if(o.developerIsSet())
        j["developer"] = o.m_Developer;
    if(o.descriptionIsSet())
        j["description"] = o.m_Description;
    if(o.downloadsIsSet())
        j["downloads"] = o.m_Downloads;
}

void from_json(const nlohmann::json& j, Inline_response_200_2& o)
{
    j.at("name").get_to(o.m_Name);
    if(j.find("picture") != j.end())
    {
        j.at("picture").get_to(o.m_Picture);
        o.m_PictureIsSet = true;
    } 
    if(j.find("starts") != j.end())
    {
        j.at("starts").get_to(o.m_Starts);
        o.m_StartsIsSet = true;
    } 
    if(j.find("tags") != j.end())
    {
        j.at("tags").get_to(o.m_Tags);
        o.m_TagsIsSet = true;
    } 
    if(j.find("developer") != j.end())
    {
        j.at("developer").get_to(o.m_Developer);
        o.m_DeveloperIsSet = true;
    } 
    if(j.find("description") != j.end())
    {
        j.at("description").get_to(o.m_Description);
        o.m_DescriptionIsSet = true;
    } 
    if(j.find("downloads") != j.end())
    {
        j.at("downloads").get_to(o.m_Downloads);
        o.m_DownloadsIsSet = true;
    } 
}

std::string Inline_response_200_2::getName() const
{
    return m_Name;
}
void Inline_response_200_2::setName(std::string const& value)
{
    m_Name = value;
}
std::string Inline_response_200_2::getPicture() const
{
    return m_Picture;
}
void Inline_response_200_2::setPicture(std::string const& value)
{
    m_Picture = value;
    m_PictureIsSet = true;
}
bool Inline_response_200_2::pictureIsSet() const
{
    return m_PictureIsSet;
}
void Inline_response_200_2::unsetPicture()
{
    m_PictureIsSet = false;
}
double Inline_response_200_2::getStarts() const
{
    return m_Starts;
}
void Inline_response_200_2::setStarts(double const value)
{
    m_Starts = value;
    m_StartsIsSet = true;
}
bool Inline_response_200_2::startsIsSet() const
{
    return m_StartsIsSet;
}
void Inline_response_200_2::unsetStarts()
{
    m_StartsIsSet = false;
}
std::string Inline_response_200_2::getTags() const
{
    return m_Tags;
}
void Inline_response_200_2::setTags(std::string const& value)
{
    m_Tags = value;
    m_TagsIsSet = true;
}
bool Inline_response_200_2::tagsIsSet() const
{
    return m_TagsIsSet;
}
void Inline_response_200_2::unsetTags()
{
    m_TagsIsSet = false;
}
std::string Inline_response_200_2::getDeveloper() const
{
    return m_Developer;
}
void Inline_response_200_2::setDeveloper(std::string const& value)
{
    m_Developer = value;
    m_DeveloperIsSet = true;
}
bool Inline_response_200_2::developerIsSet() const
{
    return m_DeveloperIsSet;
}
void Inline_response_200_2::unsetDeveloper()
{
    m_DeveloperIsSet = false;
}
std::string Inline_response_200_2::getDescription() const
{
    return m_Description;
}
void Inline_response_200_2::setDescription(std::string const& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}
bool Inline_response_200_2::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}
void Inline_response_200_2::unsetDescription()
{
    m_DescriptionIsSet = false;
}
int32_t Inline_response_200_2::getDownloads() const
{
    return m_Downloads;
}
void Inline_response_200_2::setDownloads(int32_t const value)
{
    m_Downloads = value;
    m_DownloadsIsSet = true;
}
bool Inline_response_200_2::downloadsIsSet() const
{
    return m_DownloadsIsSet;
}
void Inline_response_200_2::unsetDownloads()
{
    m_DownloadsIsSet = false;
}

}
}
}
}

