/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_response_200_1.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_response_200_1::Inline_response_200_1()
{
    m_Current_question = "";
    m_Hints = "";
    m_HintsIsSet = false;
    m_Data_type = "";
    
}

Inline_response_200_1::~Inline_response_200_1()
{
}

void Inline_response_200_1::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_response_200_1& o)
{
    j = nlohmann::json();
    j["current_question"] = o.m_Current_question;
    if(o.hintsIsSet())
        j["hints"] = o.m_Hints;
    j["data_type"] = o.m_Data_type;
}

void from_json(const nlohmann::json& j, Inline_response_200_1& o)
{
    j.at("current_question").get_to(o.m_Current_question);
    if(j.find("hints") != j.end())
    {
        j.at("hints").get_to(o.m_Hints);
        o.m_HintsIsSet = true;
    } 
    j.at("data_type").get_to(o.m_Data_type);
}

std::string Inline_response_200_1::getCurrentQuestion() const
{
    return m_Current_question;
}
void Inline_response_200_1::setCurrentQuestion(std::string const& value)
{
    m_Current_question = value;
}
std::string Inline_response_200_1::getHints() const
{
    return m_Hints;
}
void Inline_response_200_1::setHints(std::string const& value)
{
    m_Hints = value;
    m_HintsIsSet = true;
}
bool Inline_response_200_1::hintsIsSet() const
{
    return m_HintsIsSet;
}
void Inline_response_200_1::unsetHints()
{
    m_HintsIsSet = false;
}
std::string Inline_response_200_1::getDataType() const
{
    return m_Data_type;
}
void Inline_response_200_1::setDataType(std::string const& value)
{
    m_Data_type = value;
}

}
}
}
}

