/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_response_200_1_items.h
 *
 * 
 */

#ifndef Inline_response_200_1_items_H_
#define Inline_response_200_1_items_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_response_200_1_items
{
public:
    Inline_response_200_1_items();
    virtual ~Inline_response_200_1_items();

    void validate();

    /////////////////////////////////////////////
    /// Inline_response_200_1_items members

    /// <summary>
    /// 
    /// </summary>
    std::string getAppId() const;
    void setAppId(std::string const& value);
    bool appIdIsSet() const;
    void unsetApp_id();
    /// <summary>
    /// 
    /// </summary>
    std::string getAppName() const;
    void setAppName(std::string const& value);
    bool appNameIsSet() const;
    void unsetApp_name();

    friend void to_json(nlohmann::json& j, const Inline_response_200_1_items& o);
    friend void from_json(const nlohmann::json& j, Inline_response_200_1_items& o);
protected:
    std::string m_App_id;
    bool m_App_idIsSet;
    std::string m_App_name;
    bool m_App_nameIsSet;
};

}
}
}
}

#endif /* Inline_response_200_1_items_H_ */
