/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_object_5.h
 *
 * 
 */

#ifndef Inline_object_5_H_
#define Inline_object_5_H_


#include "Object.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_object_5
{
public:
    Inline_object_5();
    virtual ~Inline_object_5();

    void validate();

    /////////////////////////////////////////////
    /// Inline_object_5 members

    /// <summary>
    /// 
    /// </summary>
    bool isRestart() const;
    void setRestart(bool const value);
    bool restartIsSet() const;
    void unsetRestart();
    /// <summary>
    /// 
    /// </summary>
    nlohmann::json getResponse() const;
    void setResponse(nlohmann::json const& value);
    bool responseIsSet() const;
    void unsetResponse();

    friend void to_json(nlohmann::json& j, const Inline_object_5& o);
    friend void from_json(const nlohmann::json& j, Inline_object_5& o);
protected:
    bool m_Restart;
    bool m_RestartIsSet;
    nlohmann::json m_Response;
    bool m_ResponseIsSet;
};

}
}
}
}

#endif /* Inline_object_5_H_ */
