/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_object_1.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object_1::Inline_object_1()
{
    m_From = 0;
    m_FromIsSet = false;
    m_To = 0;
    m_ToIsSet = false;
    
}

Inline_object_1::~Inline_object_1()
{
}

void Inline_object_1::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_object_1& o)
{
    j = nlohmann::json();
    if(o.fromIsSet())
        j["from"] = o.m_From;
    if(o.toIsSet())
        j["to"] = o.m_To;
}

void from_json(const nlohmann::json& j, Inline_object_1& o)
{
    if(j.find("from") != j.end())
    {
        j.at("from").get_to(o.m_From);
        o.m_FromIsSet = true;
    } 
    if(j.find("to") != j.end())
    {
        j.at("to").get_to(o.m_To);
        o.m_ToIsSet = true;
    } 
}

int32_t Inline_object_1::getFrom() const
{
    return m_From;
}
void Inline_object_1::setFrom(int32_t const value)
{
    m_From = value;
    m_FromIsSet = true;
}
bool Inline_object_1::fromIsSet() const
{
    return m_FromIsSet;
}
void Inline_object_1::unsetFrom()
{
    m_FromIsSet = false;
}
int32_t Inline_object_1::getTo() const
{
    return m_To;
}
void Inline_object_1::setTo(int32_t const value)
{
    m_To = value;
    m_ToIsSet = true;
}
bool Inline_object_1::toIsSet() const
{
    return m_ToIsSet;
}
void Inline_object_1::unsetTo()
{
    m_ToIsSet = false;
}

}
}
}
}

