/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_response_200_2.h
 *
 * 
 */

#ifndef Inline_response_200_2_H_
#define Inline_response_200_2_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_response_200_2
{
public:
    Inline_response_200_2();
    virtual ~Inline_response_200_2();

    void validate();

    /////////////////////////////////////////////
    /// Inline_response_200_2 members

    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getPicture() const;
    void setPicture(std::string const& value);
    bool pictureIsSet() const;
    void unsetPicture();
    /// <summary>
    /// 
    /// </summary>
    double getStarts() const;
    void setStarts(double const value);
    bool startsIsSet() const;
    void unsetStarts();
    /// <summary>
    /// 
    /// </summary>
    std::string getTags() const;
    void setTags(std::string const& value);
    bool tagsIsSet() const;
    void unsetTags();
    /// <summary>
    /// 
    /// </summary>
    std::string getDeveloper() const;
    void setDeveloper(std::string const& value);
    bool developerIsSet() const;
    void unsetDeveloper();
    /// <summary>
    /// 
    /// </summary>
    std::string getDescription() const;
    void setDescription(std::string const& value);
    bool descriptionIsSet() const;
    void unsetDescription();
    /// <summary>
    /// 
    /// </summary>
    int32_t getDownloads() const;
    void setDownloads(int32_t const value);
    bool downloadsIsSet() const;
    void unsetDownloads();

    friend void to_json(nlohmann::json& j, const Inline_response_200_2& o);
    friend void from_json(const nlohmann::json& j, Inline_response_200_2& o);
protected:
    std::string m_Name;

    std::string m_Picture;
    bool m_PictureIsSet;
    double m_Starts;
    bool m_StartsIsSet;
    std::string m_Tags;
    bool m_TagsIsSet;
    std::string m_Developer;
    bool m_DeveloperIsSet;
    std::string m_Description;
    bool m_DescriptionIsSet;
    int32_t m_Downloads;
    bool m_DownloadsIsSet;
};

}
}
}
}

#endif /* Inline_response_200_2_H_ */
