/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Inline_response_200_1.h
 *
 * 
 */

#ifndef Inline_response_200_1_H_
#define Inline_response_200_1_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Inline_response_200_1
{
public:
    Inline_response_200_1();
    virtual ~Inline_response_200_1();

    void validate();

    /////////////////////////////////////////////
    /// Inline_response_200_1 members

    /// <summary>
    /// 
    /// </summary>
    std::string getName() const;
    void setName(std::string const& value);
    bool nameIsSet() const;
    void unsetName();
    /// <summary>
    /// 
    /// </summary>
    std::string getPicture() const;
    void setPicture(std::string const& value);
    bool pictureIsSet() const;
    void unsetPicture();
    /// <summary>
    /// 
    /// </summary>
    double getPrice() const;
    void setPrice(double const value);
    bool priceIsSet() const;
    void unsetPrice();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string>& getTags();
    void setTags(std::vector<std::string> const& value);
    bool tagsIsSet() const;
    void unsetTags();
    /// <summary>
    /// 
    /// </summary>
    std::string get() const;
    void set(std::string const& value);
    bool IsSet() const;
    void unset();

    friend void to_json(nlohmann::json& j, const Inline_response_200_1& o);
    friend void from_json(const nlohmann::json& j, Inline_response_200_1& o);
protected:
    std::string m_Name;
    bool m_NameIsSet;
    std::string m_Picture;
    bool m_PictureIsSet;
    double m_Price;
    bool m_PriceIsSet;
    std::vector<std::string> m_Tags;
    bool m_TagsIsSet;
    std::string m_;
    bool m_IsSet;
};

}
}
}
}

#endif /* Inline_response_200_1_H_ */
