/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_object_3.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object_3::Inline_object_3()
{
    m_App_objIsSet = false;
    
}

Inline_object_3::~Inline_object_3()
{
}

void Inline_object_3::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Inline_object_3& o)
{
    j = nlohmann::json();
    if(o.appObjIsSet())
        j["app_obj"] = o.m_App_obj;
}

void from_json(const nlohmann::json& j, Inline_object_3& o)
{
    if(j.find("app_obj") != j.end())
    {
        j.at("app_obj").get_to(o.m_App_obj);
        o.m_App_objIsSet = true;
    } 
}

nlohmann::json Inline_object_3::getAppObj() const
{
    return m_App_obj;
}
void Inline_object_3::setAppObj(nlohmann::json const& value)
{
    m_App_obj = value;
    m_App_objIsSet = true;
}
bool Inline_object_3::appObjIsSet() const
{
    return m_App_objIsSet;
}
void Inline_object_3::unsetApp_obj()
{
    m_App_objIsSet = false;
}

}
}
}
}

