/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Interval.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Interval::Interval()
{
    m_Start = 0;
    m_End = 0;
    
}

Interval::~Interval()
{
}

void Interval::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Interval& o)
{
    j = nlohmann::json();
    j["start"] = o.m_Start;
    j["end"] = o.m_End;
}

void from_json(const nlohmann::json& j, Interval& o)
{
    j.at("start").get_to(o.m_Start);
    j.at("end").get_to(o.m_End);
}

int32_t Interval::getStart() const
{
    return m_Start;
}
void Interval::setStart(int32_t const value)
{
    m_Start = value;
}
int32_t Interval::getEnd() const
{
    return m_End;
}
void Interval::setEnd(int32_t const value)
{
    m_End = value;
}

}
}
}
}

