/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Object.h
 *
 * 
 */

#ifndef Object_H_
#define Object_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Object
{
public:
    Object();
    virtual ~Object();

    void validate();

    /////////////////////////////////////////////
    /// Object members

    /// <summary>
    /// 
    /// </summary>
    

    friend void to_json(nlohmann::json& j, const Object& o);
    friend void from_json(const nlohmann::json& j, Object& o);
protected:
};

}
}
}
}

#endif /* bject_H_ */
