/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Object.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Object::Object()
{
    
}

Object::~Object()
{
}

void Object::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Object& o)
{
    j = nlohmann::json();
}

void from_json(const nlohmann::json& j, Object& o)
{
}

}
}
}
}

