/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Prot_app_info.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Prot_app_info::Prot_app_info()
{
    m_Form_id = 0;
    m_Form_name = "";
    
}

Prot_app_info::~Prot_app_info()
{
}

void Prot_app_info::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Prot_app_info& o)
{
    j = nlohmann::json();
    j["form_id"] = o.m_Form_id;
    j["form_name"] = o.m_Form_name;
}

void from_json(const nlohmann::json& j, Prot_app_info& o)
{
    j.at("form_id").get_to(o.m_Form_id);
    j.at("form_name").get_to(o.m_Form_name);
}

int32_t Prot_app_info::getFormId() const
{
    return m_Form_id;
}
void Prot_app_info::setFormId(int32_t const value)
{
    m_Form_id = value;
}
std::string Prot_app_info::getFormName() const
{
    return m_Form_name;
}
void Prot_app_info::setFormName(std::string const& value)
{
    m_Form_name = value;
}

}
}
}
}

