/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Scheduler.h
 *
 * 
 */

#ifndef Scheduler_H_
#define Scheduler_H_


#include "Task.h"
#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Scheduler
{
public:
    Scheduler();
    virtual ~Scheduler();

    void validate();

    /////////////////////////////////////////////
    /// Scheduler members

    /// <summary>
    /// 
    /// </summary>
    std::string getPolicy() const;
    void setPolicy(std::string const& value);
    bool policyIsSet() const;
    void unsetPolicy();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Task>& getIntervalMap();
    void setIntervalMap(std::vector<Task> const& value);
    bool intervalMapIsSet() const;
    void unsetInterval_map();

    friend void to_json(nlohmann::json& j, const Scheduler& o);
    friend void from_json(const nlohmann::json& j, Scheduler& o);
protected:
    std::string m_Policy;
    bool m_PolicyIsSet;
    std::vector<Task> m_Interval_map;
    bool m_Interval_mapIsSet;
};

}
}
}
}

#endif /* Scheduler_H_ */
