/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Scheduler.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Scheduler::Scheduler()
{
    m_Policy = "";
    m_PolicyIsSet = false;
    m_Interval_mapIsSet = false;
    
}

Scheduler::~Scheduler()
{
}

void Scheduler::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Scheduler& o)
{
    j = nlohmann::json();
    if(o.policyIsSet())
        j["policy"] = o.m_Policy;
    if(o.intervalMapIsSet() || !o.m_Interval_map.empty())
        j["interval_map"] = o.m_Interval_map;
}

void from_json(const nlohmann::json& j, Scheduler& o)
{
    if(j.find("policy") != j.end())
    {
        j.at("policy").get_to(o.m_Policy);
        o.m_PolicyIsSet = true;
    } 
    if(j.find("interval_map") != j.end())
    {
        j.at("interval_map").get_to(o.m_Interval_map);
        o.m_Interval_mapIsSet = true;
    } 
}

std::string Scheduler::getPolicy() const
{
    return m_Policy;
}
void Scheduler::setPolicy(std::string const& value)
{
    m_Policy = value;
    m_PolicyIsSet = true;
}
bool Scheduler::policyIsSet() const
{
    return m_PolicyIsSet;
}
void Scheduler::unsetPolicy()
{
    m_PolicyIsSet = false;
}
std::vector<Task>& Scheduler::getIntervalMap()
{
    return m_Interval_map;
}
void Scheduler::setIntervalMap(std::vector<Task> const& value)
{
    m_Interval_map = value;
    m_Interval_mapIsSet = true;
}
bool Scheduler::intervalMapIsSet() const
{
    return m_Interval_mapIsSet;
}
void Scheduler::unsetInterval_map()
{
    m_Interval_mapIsSet = false;
}

}
}
}
}

