/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Tasker.h
 *
 * 
 */

#ifndef Tasker_H_
#define Tasker_H_


#include "Task.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Tasker
{
public:
    Tasker();
    virtual ~Tasker();

    void validate();

    /////////////////////////////////////////////
    /// Tasker members

    /// <summary>
    /// 
    /// </summary>
    std::vector<Task>& getTasks();
    void setTasks(std::vector<Task> const& value);
    bool tasksIsSet() const;
    void unsetTasks();

    friend void to_json(nlohmann::json& j, const Tasker& o);
    friend void from_json(const nlohmann::json& j, Tasker& o);
protected:
    std::vector<Task> m_Tasks;
    bool m_TasksIsSet;
};

}
}
}
}

#endif /* Tasker_H_ */
