/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Tasker.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Tasker::Tasker()
{
    m_TasksIsSet = false;
    
}

Tasker::~Tasker()
{
}

void Tasker::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const Tasker& o)
{
    j = nlohmann::json();
    if(o.tasksIsSet() || !o.m_Tasks.empty())
        j["tasks"] = o.m_Tasks;
}

void from_json(const nlohmann::json& j, Tasker& o)
{
    if(j.find("tasks") != j.end())
    {
        j.at("tasks").get_to(o.m_Tasks);
        o.m_TasksIsSet = true;
    } 
}

std::vector<Task>& Tasker::getTasks()
{
    return m_Tasks;
}
void Tasker::setTasks(std::vector<Task> const& value)
{
    m_Tasks = value;
    m_TasksIsSet = true;
}
bool Tasker::tasksIsSet() const
{
    return m_TasksIsSet;
}
void Tasker::unsetTasks()
{
    m_TasksIsSet = false;
}

}
}
}
}

