/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * User_params.h
 *
 * 
 */

#ifndef User_params_H_
#define User_params_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  User_params
{
public:
    User_params();
    virtual ~User_params();

    void validate();

    /////////////////////////////////////////////
    /// User_params members

    /// <summary>
    /// 
    /// </summary>
    std::string getTimeZone() const;
    void setTimeZone(std::string const& value);
    bool timeZoneIsSet() const;
    void unsetTime_zone();

    friend void to_json(nlohmann::json& j, const User_params& o);
    friend void from_json(const nlohmann::json& j, User_params& o);
protected:
    std::string m_Time_zone;
    bool m_Time_zoneIsSet;
};

}
}
}
}

#endif /* User_params_H_ */
