/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * User_apps_get_response.h
 *
 * 
 */

#ifndef User_apps_get_response_H_
#define User_apps_get_response_H_


#include <string>
#include "Object.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  User_apps_get_response
{
public:
    User_apps_get_response();
    virtual ~User_apps_get_response();

    void validate();

    /////////////////////////////////////////////
    /// User_apps_get_response members

    /// <summary>
    /// 
    /// </summary>
    int32_t getAppId() const;
    void setAppId(int32_t const value);
    bool appIdIsSet() const;
    void unsetApp_id();
    /// <summary>
    /// 
    /// </summary>
    std::string getAppName() const;
    void setAppName(std::string const& value);
    bool appNameIsSet() const;
    void unsetApp_name();
    /// <summary>
    /// 
    /// </summary>
    nlohmann::json getQaHistory() const;
    void setQaHistory(nlohmann::json const& value);
    bool qaHistoryIsSet() const;
    void unsetQa_history();

    friend void to_json(nlohmann::json& j, const User_apps_get_response& o);
    friend void from_json(const nlohmann::json& j, User_apps_get_response& o);
protected:
    int32_t m_App_id;
    bool m_App_idIsSet;
    std::string m_App_name;
    bool m_App_nameIsSet;
    nlohmann::json m_Qa_history;
    bool m_Qa_historyIsSet;
};

}
}
}
}

#endif /* User_apps_get_response_H_ */
