/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "When.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

When::When()
{
    m_After = "";
    m_Maximum_delayIsSet = false;
    
}

When::~When()
{
}

void When::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const When& o)
{
    j = nlohmann::json();
    j["after"] = o.m_After;
    j["minumum_delay"] = o.m_Minumum_delay;
    if(o.maximumDelayIsSet())
        j["maximum_delay"] = o.m_Maximum_delay;
}

void from_json(const nlohmann::json& j, When& o)
{
    j.at("after").get_to(o.m_After);
    j.at("minumum_delay").get_to(o.m_Minumum_delay);
    if(j.find("maximum_delay") != j.end())
    {
        j.at("maximum_delay").get_to(o.m_Maximum_delay);
        o.m_Maximum_delayIsSet = true;
    } 
}

std::string When::getAfter() const
{
    return m_After;
}
void When::setAfter(std::string const& value)
{
    m_After = value;
}
Duration When::getMinumumDelay() const
{
    return m_Minumum_delay;
}
void When::setMinumumDelay(Duration const& value)
{
    m_Minumum_delay = value;
}
Duration When::getMaximumDelay() const
{
    return m_Maximum_delay;
}
void When::setMaximumDelay(Duration const& value)
{
    m_Maximum_delay = value;
    m_Maximum_delayIsSet = true;
}
bool When::maximumDelayIsSet() const
{
    return m_Maximum_delayIsSet;
}
void When::unsetMaximum_delay()
{
    m_Maximum_delayIsSet = false;
}

}
}
}
}

