/**
* prot
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * When.h
 *
 * 
 */

#ifndef When_H_
#define When_H_


#include "Duration.h"
#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  When
{
public:
    When();
    virtual ~When();

    void validate();

    /////////////////////////////////////////////
    /// When members

    /// <summary>
    /// Tag of the task, that this should be after
    /// </summary>
    std::string getAfter() const;
    void setAfter(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    Duration getMinumumDelay() const;
    void setMinumumDelay(Duration const& value);
    /// <summary>
    /// 
    /// </summary>
    Duration getMaximumDelay() const;
    void setMaximumDelay(Duration const& value);
    bool maximumDelayIsSet() const;
    void unsetMaximum_delay();

    friend void to_json(nlohmann::json& j, const When& o);
    friend void from_json(const nlohmann::json& j, When& o);
protected:
    std::string m_After;

    Duration m_Minumum_delay;

    Duration m_Maximum_delay;
    bool m_Maximum_delayIsSet;
};

}
}
}
}

#endif /* When_H_ */
