openapi: 3.0.0
info:
  title: prot
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/user/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/user.v1.json
        '404':
          description: Not Found
    delete:
      summary: ''
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    patch:
      summary: ''
      operationId: ''
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                forward_projection:
                  type: integer
                backwards_projection:
                  type: integer
  /user:
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                required:
                  - user_id
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                user_id:
                  type: string
              required:
                - username
                - user_id
  '/user/{userId}/tasks':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  description: task.v1.json as reference
    post:
      summary: ''
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type_of_task:
                  type: string
                  enum:
                    - auto
                    - user
                task:
                  type: object
                  description: auto or user... oneOf
              required:
                - type_of_task
                - task
  '/user/{userId}/task/{taskId}':
    parameters:
      - schema:
          type: string
        name: taskId
        in: path
        required: true
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '404':
          description: Not Found
    delete:
      summary: ''
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
  '/user/{developer}/app':
    parameters:
      - schema:
          type: string
        name: developer
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: 'Returns all the developer, apps_names submited'
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        app_id:
                          type: string
                        app_name:
                          type: string
      description: ''
    post:
      summary: ''
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '406':
          description: Not Acceptable
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                app_obj:
                  type: object
  '/user/{developer}/app/{appId}':
    parameters:
      - schema:
          type: string
        name: developer
        in: path
        required: true
      - schema:
          type: integer
        name: appId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  app_obj:
                    type: object
        '401':
          description: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties: {}
    put:
      summary: ''
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                app_obj:
                  type: object
      description: ''
    delete:
      summary: ''
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      description: ''
  '/user/{userId}/apps':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/user_apps_get_response.v1.yaml
        '404':
          description: Not Found
  '/user/{userId}/apps/{installAppId}':
    parameters:
      - schema:
          type: integer
        name: installAppId
        in: path
        required: true
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/user_apps_get_response.v1.yaml
        '404':
          description: Not Found
      description: ''
    post:
      summary: ''
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    delete:
      summary: ''
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
  '/user/{userId}/questionary/{appId}':
    parameters:
      - schema:
          type: integer
        name: appId
        in: path
        required: true
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_question:
                    type: string
                  hints:
                    type: string
                  data_type:
                    type: string
                  type_details:
                    type: object
                required:
                  - current_question
                  - data_type
        '403':
          description: Forbidden
        '404':
          description: Not Found
      description: Returns the current question pending to be responded
    post:
      summary: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                restart:
                  type: boolean
                response:
                  type: object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
        '404':
          description: Not Found
  /apps:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/prot_app_info.v1.json
  '/apps/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/prot_app_info.v1.json
        '404':
          description: Not Found
      description: ''
components:
  schemas: {}
